### ISSUE TITLE
[建议]: 增加区域查询功能，和细粒度的R0分析曲线

### ISSUE THREAD

**Issue by renqibing** [Bai-Yu-Lan/SH-COVID19#1]
为了提高实用性和扩散度，建议增加区域查询功能，精准定位到小区一级的位置，如果辅以小区一级的细粒度的R0分析曲线就更好了，真的可以为我们灵活协调疫情防控做出贡献。

**Comment by BillXSY** [comment]
暂时无法获取小区/街道层面感染人数，只能获取区县级别的数据，所以无法做到细粒度的R0/Rt分析

**Comment by jinyh** [comment]
您好，目前数据公开的粒度只到行政区级别，没有街道，更不到小区一级啊。
