### ISSUE TITLE
增加解除医学观察的人数

### ISSUE THREAD

**Issue by lee8763** [Bai-Yu-Lan/SH-COVID19#2]
您好,建议添加"解除医学观察的人数"

**Comment by BillXSY** [comment]
考虑到在http://reopen.baiyulan.org.cn/#上优先展示重要信息，暂时没有在网页上新增相关栏目的打算，可以通过“医疗资源使用情况”了解方舱医院/医院的使用情况。

关于解除医学观察人数的数据，后续会整理公布到这个库里。
