### ISSUE TITLE
部分数据未展示于网站地图上

### ISSUE THREAD

**Issue by EuropeanWithSSR** [Bai-Yu-Lan/SH-COVID19#3]
例1：博山东路20弄，地图上显示**从未**出现阳性，但在原始数据中有多日的记录，最近一次是4月28日。
例2：平武路150弄，在原始数据中也有多日记录，在地图上仅显示4月13日**一条**。

还有很多其他地点的数据同样没有或没有完整出现在地图上，能否做一下修复？另外，数据未出现在地图上是否影响Rt analysis？谢谢！

**Comment by BillXSY** [comment]
已修复少数POI位置与通报情况不匹配的问题

**Comment by BillXSY** [comment]
感谢指出问题，已修复少数POI位置与通报情况数据不匹配的问题。疫情可视化与Rt analysis不回相互影响。
